on:
  pull_request:
    branches: "main"

jobs:
  test_abq:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: abq
            version: "1.8.1"
            os: macos-12 # intel
          - name: abq
            version: "1.8.1"
            os: macos-14 # arm

          - name: abq@1
            version: "1.8.1"
            os: macos-12 # intel
          - name: abq@1
            version: "1.8.1"
            os: macos-14 # arm
    steps:
      - uses: actions/checkout@v3

      - name: Install abq & run it
        run: |
          set -o pipefail
          ! command -v abq
          brew install ./Formula/${{ matrix.name }}.rb 2>&1 | tee install-output.txt
          abq --version | grep ${{ matrix.version }}

      - name: Ensure the integrity was verified
        run: '! grep "Cannot verify integrity of" install-output.txt'

  test_abq_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: abq
            version: "1.8.1"
          - name: abq@1
            version: "1.8.1"
    steps:
      - name: Install homebrew
        uses: Homebrew/actions/setup-homebrew@5caa94335a28d8fdf5a478ae8586f2da40a0a989
      - name: Install abq & run it
        run: |
          set -o pipefail
          ! command -v abq
          brew install ${{ matrix.name }}
          abq --version | grep ${{ matrix.version }}
