on:
  pull_request:
    branches: "main"

jobs:
  test_abq:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: abq
            version: "1.7.4"
            os: macos-12 # intel
          - name: abq
            version: "1.7.4"
            os: macos-14 # arm
          - name: abq
            version: "1.7.4"
            os: ubuntu-latest

          - name: abq@1
            version: "1.7.4"
            os: macos-12 # intel
          - name: abq@1
            version: "1.7.4"
            os: macos-14 # arm
          - name: abq@1
            version: "1.7.4"
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install abq & run it
        run: |
          set -o pipefail
          ! command -v abq
          brew install ./Formula/${{ matrix.name }}.rb 2>&1 | tee install-output.txt
          abq --version | grep ${{ matrix.version }}

      - name: Ensure the integrity was verified
        run: '! grep "Cannot verify integrity of" install-output.txt'
