on:
  pull_request:
    branches: [main]

jobs:
  test_captain:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: captain
            version: "1.18.1"
            os: macos-13 # intel
          - name: captain
            version: "1.18.1"
            os: macos-14 # arm

          - name: captain@1
            version: "1.18.1"
            os: macos-13 # intel
          - name: captain@1
            version: "1.18.1"
            os: macos-14 # arm

    steps:
      - uses: actions/checkout@v3

      - name: Install captain & run it
        run: |
          set -o pipefail
          ! command -v captain
          brew install ./Formula/${{ matrix.name }}.rb 2>&1 | tee install-output.txt
          captain --version | grep ${{ matrix.version }}

      - name: Ensure the integrity was verified
        run: '! grep "Cannot verify integrity of" install-output.txt'

  test_captain_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: captain
            version: "1.18.1"
          - name: captain@1
            version: "1.18.1"
    steps:
      - name: Install homebrew
        uses: Homebrew/actions/setup-homebrew@5caa94335a28d8fdf5a478ae8586f2da40a0a989
      - name: Install captain
        run: |
          set -o pipefail
          ! command -v captain
          brew install ${{ matrix.name }}
          captain --version | grep ${{ matrix.version }}
