on:
  pull_request:
    branches: "main"

jobs:
  test_abq:
    runs-on: macos-12
    strategy:
      matrix:
        include:
          - name: abq
            version: "1.6.3"
          - name: abq@1
            version: "1.6.3"
    steps:
      - uses: actions/checkout@v3
        with:
          path: homebrew-fake-tap-name # give it a fake name so we don't accidentally pull the one from github

      - name: move it to the right directory
        run: |
          mkdir -p homebrew-tap /usr/local/Homebrew/Library/Taps/rwx-research
          mv homebrew-fake-tap-name /usr/local/Homebrew/Library/Taps/rwx-research/

      - name: Install abq & run it
        run: |
          set -o pipefail
          brew install rwx-research/fake-tap-name/${{ matrix.name }} 2>&1 | tee install-output.txt
          abq --version | grep ${{ matrix.version }}

      - name: Ensure the integrity was verified
        run: '! grep "Cannot verify integrity of" install-output.txt'

  test_captain:
    runs-on: macos-12
    strategy:
      matrix:
        include:
          - name: captain
            version: "1.11.6"
          - name: captain@1
            version: "1.11.6"
    steps:
      - uses: actions/checkout@v3
        with:
          path: homebrew-fake-tap-name # give it a fake name so we don't accidentally pull the one from github

      - name: move it to the right directory
        run: |
          mkdir -p homebrew-tap /usr/local/Homebrew/Library/Taps/rwx-research
          mv homebrew-fake-tap-name /usr/local/Homebrew/Library/Taps/rwx-research/

      - name: Install captain & run it
        run: |
          set -o pipefail
          brew install rwx-research/fake-tap-name/${{ matrix.name }} 2>&1 | tee install-output.txt
          captain --version | grep ${{ matrix.version }}

      - name: Ensure the integrity was verified
        run: '! grep "Cannot verify integrity of" install-output.txt'

  test_mint:
    runs-on: macos-12
    strategy:
      matrix:
        include:
          - name: mint
            version: "0.0.7"
    steps:
      - uses: actions/checkout@v3
        with:
          path: homebrew-fake-tap-name # give it a fake name so we don't accidentally pull the one from github

      - name: move it to the right directory
        run: |
          mkdir -p homebrew-tap /usr/local/Homebrew/Library/Taps/rwx-research
          mv homebrew-fake-tap-name /usr/local/Homebrew/Library/Taps/rwx-research/

      - name: Install mint & run it
        run: |
          set -o pipefail
          brew install rwx-research/fake-tap-name/${{ matrix.name }} 2>&1 | tee install-output.txt
          mint --version | grep ${{ matrix.version }}

      - name: Ensure the integrity was verified
        run: '! grep "Cannot verify integrity of" install-output.txt'
