on:
  pull_request:
    branches: "main"

jobs:
  test_mint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: mint
            version: "0.1.1"
            os: macos-12 # intel
          - name: mint
            version: "0.1.1"
            os: macos-14 # arm
    steps:
      - uses: actions/checkout@v3

      - name: Install mint & run it
        run: |
          set -o pipefail
          ! command -v mint
          brew install ./Formula/${{ matrix.name }}.rb 2>&1 | tee install-output.txt
          mint --version | grep ${{ matrix.version }}

      - name: Ensure the integrity was verified
        run: '! grep "Cannot verify integrity of" install-output.txt'

  test_mint_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: mint
            version: "0.1.1"
    steps:
      - name: Install homebrew
        uses: Homebrew/actions/setup-homebrew@5caa94335a28d8fdf5a478ae8586f2da40a0a989
      - name: Install mint
        run: |
          set -o pipefail
          ! command -v abq
          brew install rwx-research/tap/${{ matrix.name }}
          mint --version | grep ${{ matrix.version }}
