on:
  pull_request:
    branches: [main]

jobs:
  test_mint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: mint
            version: "1.7.0"
            os: macos-15-intel
          - name: mint
            version: "1.7.0"
            os: macos-latest # arm
    steps:
      - uses: actions/checkout@v3

      - name: Install mint & run it
        run: |
          set -o pipefail
          ! command -v mint
          brew install ./Formula/${{ matrix.name }}.rb 2>&1 | tee install-output.txt
          mint --version | grep ${{ matrix.version }}
        env:
          HOMEBREW_DEVELOPER: 1

      - name: Ensure the integrity was verified
        run: '! grep "Cannot verify integrity of" install-output.txt'

  test_mint_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: mint
            version: "1.7.0"
    steps:
      - uses: actions/checkout@v3

      - name: Install homebrew
        uses: Homebrew/actions/setup-homebrew@5caa94335a28d8fdf5a478ae8586f2da40a0a989
      - name: Configure Linux sandbox
        run: |
          sudo apt-get update
          sudo apt-get install --yes bubblewrap
          sudo sysctl -w kernel.unprivileged_userns_clone=1
          sudo sysctl -w user.max_user_namespaces=28633
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0 || true
      - name: Install mint
        run: |
          set -o pipefail
          ! command -v mint
          brew trust --formula rwx-research/tap/${{ matrix.name }}
          brew install --formula ./Formula/${{ matrix.name }}.rb 2>&1 | tee install-output.txt
          mint --version | grep ${{ matrix.version }}
        env:
          HOMEBREW_DEVELOPER: 1

      - name: Ensure the integrity was verified
        run: '! grep "Cannot verify integrity of" install-output.txt'
